### ISSUE TITLE
Update of sensor.myfitnesspal_tomas is taking over 10 seconds

### ISSUE THREAD

**Issue by helto4real** [helto4real/custom_component_myfitnesspal#1]
Underlying scraping API I use is taking a long time updating. Since it is syncronous it make this warning. I will investigate if there is a better way to code this.

**Comment by bachoo786** [comment]
Hi there

How often is this component meant to update? After some change in the myfitnesspal app would I see the update right away on this component in HA? 

Thanks.

**Comment by helto4real** [comment]
> Hi there
> 
> How often is this component meant to update? After some change in the myfitnesspal app would I see the update right away on this component in HA?
> 
> Thanks.

It is using "pull" to refresh values at the default refresh intervall for sensors. That is currently 30s. It would not be wise to do it more often since it will be a bad way to use the service and could lead to banned accounts.

**Comment by bachoo786** [comment]
> > Hi there
> > How often is this component meant to update? After some change in the myfitnesspal app would I see the update right away on this component in HA?
> > Thanks.
> 
> It is using "pull" to refresh values at the default refresh intervall for sensors. That is currently 30s. It would not be wise to do it more often since it will be a bad way to use the service and could lead to banned accounts.

Oh right I see. The trouble I am having is when I update myfitnesspal app I don't see the changes on HA. It will only update once and wont update again at all.
