### ISSUE TITLE
Overview which data should be exposed to Home Assistant

### ISSUE THREAD

**Issue by smartmatic** [helto4real/custom_component_myfitnesspal#22]
Hello,

thank you for this custom integration. I‘ve successfully setup the Sensor but only my weight is available as entity.
I have also expected that additional data like calories, training or steps etc. are exposed to HA.

Is there an overview which data should be exposed to Home Assistant?

**Comment by helto4real** [comment]
There are alot of values as attributes. I had to choose one of them as state but you can use any of the attributes

**Comment by smartmatic** [comment]
Where to find the attributes. I see only one entity

![1732E8ED-2451-4E06-911D-5E7605993325](https://user-images.githubusercontent.com/74932663/173231970-dd49e627-488d-4308-88d5-2c6937426645.jpeg)

**Comment by smartmatic** [comment]
Sorry got it

**Comment by smartmatic** [comment]
Thanks, got it. Ticket can be closed!

**Comment by helto4real** [comment]
Thanks
