### ISSUE TITLE
cannot unpack non-iterable int object??

### ISSUE THREAD

**Issue by mkono87** [helto4real/custom_component_myfitnesspal#7]
`2021-01-05 15:43:57 WARNING (MainThread) [homeassistant.config_entries] Config entry for my_fitnesspal not ready yet. Retrying in 5 seconds
2021-01-05 15:44:05 ERROR (MainThread) [custom_components.my_fitnesspal] Error fetching my_fitnesspal data: cannot unpack non-iterable int object`

After signing in, the intergration says config has been created however no sensor is created and that is what shows in the logs.

I tried both my username and email when signing it both same issue.

**Comment by Heggeg** [comment]
I get the samre Error Message. Can u please take look? :)

**Comment by helto4real** [comment]
Please try to upgrade to latest version. @mkono87 @heggeg

**Comment by helto4real** [comment]
Reopen if still experience problem.
