### ISSUE TITLE
Installation doesnt show up

### ISSUE THREAD

**Issue by MariusHerget** [helto4real/custom_component_myfitnesspal#9]
When installing the custom component via Hacs it does not show up under integrations or in the dev tool.

Log: 
`2021-05-07 16:40:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration my_fitnesspal which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

Verison: 0.7a

**Comment by helto4real** [comment]
The log always show this. This integration is currently broken. Will check it out during the weekend

**Comment by helto4real** [comment]
@MariusHerget looks like the python package is broken. So it is not much I can do.

**Comment by helto4real** [comment]
I upgraded the pypi package now. Please retry @MariusHerget

**Comment by MariusHerget** [comment]
@helto4real I updated to 0.9a. Restarted Hassio. 

It works :) I will watch out for any unwanted behavior. Thanks for now!
